---
- name: Clear leftover containers and dirs after an RKE cluster delete (with either __rke remove__ or via Rancher server UI)
    # per https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/
  hosts: ubuntu-rke
  tasks:
    - name: stop all docker containers
      shell: docker stop $(docker ps -a -q)
      ignore_errors: true
    - name: remove all docker containers
      shell: docker rm -v $(docker ps -a -q)
      ignore_errors: true
    - name: remove all docker volumes
      shell: docker volume rm $(docker volume ls -q) 
      ignore_errors: true      
    # - name: remove all docker images
    #   shell: docker rmi $(docker images -q)
    #   ignore_errors: true   

    - name: clean Kubernetes components and secrets mounts
      shell: for mount in $(mount | grep tmpfs | grep '/var/lib/kubelet' | awk '{ print $3 }') /var/lib/kubelet /var/lib/rancher; do sudo umount $mount; done
      ignore_errors: true   

    - name: clean directories
      shell: sudo rm -rf /etc/ceph \ /etc/cni \ /etc/kubernetes \ /opt/cni \ /opt/rke \ /run/secrets/kubernetes.io \ /run/calico \ /run/flannel \ /var/lib/calico \ /var/lib/etcd \ /var/lib/cni \ /var/lib/kubelet \ /var/lib/rancher/rke/log \ /var/log/containers \ /var/log/kube-audit \ /var/log/pods \ /var/run/calico
      ignore_errors: true   

